<?php

namespace App\Facades;

use Illuminate\Support\Facades\Facade;

class ShopSetting extends Facade
{
    protected static function getFacadeAccessor(): string
    {
        return 'shop.setting'; // TODO: Change the autogenerated stub
    }
}
